### EJEMPLO 1

In [1]:
# Creando un vector

from numpy import array
# Definiendo el vector
v = array([1, 2, 3])
print(v)

[1 2 3]


### EJEMPLO 2

In [2]:
# Suma de vectores

from numpy import array
# Definiendo el primer y segundo vector
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
# Sumando vectores
c = a + b
print(c)

[1 2 3]
[1 2 3]
[2 4 6]


### EJEMPLO 3

In [4]:
# Resta de vectores

from numpy import array
# Definiendo el primer y segundo vector
a = array([1, 2, 3])
print(a)
b = array([-1, 2, 0])
print(b)
# Restando vectores
c = a - b
print(c)

[1 2 3]
[-1  2  0]
[2 0 3]


### EJEMPLO 4

In [5]:
# Multiplicación de vectores

from numpy import array
# Definiendo el primer y segundo vector
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
# Multiplicando vectores
c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


### EJEMPLO 5

In [6]:
# División de vectores

from numpy import array
# Definiendo el primer y segundo vector
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
# Dividiendo vectores
c = a / b
print(c)

[1 2 3]
[1 2 3]
[1. 1. 1.]


### EJEMPLO 6
La función para calcular el producto punto es `dot()`

In [3]:
# Producto punto

from numpy import array
# Definiendo el primer y segundo vector
a, b = array([1, 2, 3]), array([1, 2, 3])
print(a)
print(b)
# Calculando el producto punto
c = a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


### EJEMPLO 7

In [4]:
# Multiplicación por un escalar

from numpy import array
# Definiendo el vector
a = array([1, 2, 3])
print(a)
# Definiendo el escalar
s = .5
print(s)
# Multiplicación
c = s * a
print(c)

[1 2 3]
0.5
[0.5 1.  1.5]
