### EJEMPLO 1
Es necesario usar la función `lu()` para obtener la descomposición LU.

In [1]:
# Descomposición LU

from numpy import array
from scipy.linalg import lu
# Definiendo una matriz cuadrada
A = array([
    [1, 2, 3],
    [5, 6, 7],
    [8, 9, 10]
])
print(A)
# Factorizando
P, L, U = lu(A)
print(P)
print(L)
print(U)
# Reconstruyendo
B = P.dot(L).dot(U)
print(B)

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.125      1.         0.        ]
 [0.625      0.42857143 1.        ]]
[[8.00000000e+00 9.00000000e+00 1.00000000e+01]
 [0.00000000e+00 8.75000000e-01 1.75000000e+00]
 [0.00000000e+00 0.00000000e+00 4.16333634e-17]]
[[ 1.  2.  3.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


### EJEMPLO 2
Para obtener la descomposición QR se utiliza la función `qr()`. 
Por default, la función regresa las matrices $Q$ y $R$ con una dimensión más pequeña. Para cambiar esto y obtener las dimensiones esperadas, usamos el argumento *'complete'*. 

In [3]:
# Descomposición QR

from numpy import array
from numpy.linalg import qr
# Definiendo una matriz rectangular
A = array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(A)
# Factorización
Q, R = qr(A, 'complete')
print(Q)
print(R)
# Reconstruyendo
B = Q.dot(R)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


### EJEMPLO 3
Para obtener la descomposición de Cholesky debemos usar la función `cholesky()`.

In [5]:
# Descomposición de Cholesky

from numpy import array
from numpy.linalg import cholesky
# Definiendo una matriz simétrica
A = array([
    [2, 1, 1],
    [1, 2, 1],
    [1, 1, 2]
])
print(A)
# Factorización
L = cholesky(A)
print(L)
# Reconstruyendo
B = L.dot(L.T)
print(B)

[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
