### EJEMPLO 1

In [1]:
# Crear una matriz

from numpy import array
A = array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)

[[1 2 3]
 [4 5 6]]


### EJEMPLO 2

In [2]:
# Sumar dos matrices

from numpy import array
# Definiendo la primera y segunda matriz
A, B = array([
    [1, 2, 3],
    [4, 5, 6]
]),  array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)
print(B)
# Sumando las matrices
C = A + B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


### EJEMPLO 3

In [3]:
# Restar dos matrices

from numpy import array
# Definiendo la primera y segunda matriz
A, B = array([
    [1, 2, 3],
    [4, 5, 6]
]),  array([
    [2, 4, 6],
    [8, 10, 12]
])
print(A)
print(B)
# Restando las matrices
C = A - B
print(C)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[-1 -2 -3]
 [-4 -5 -6]]


### EJEMPLO 4

In [4]:
# Multiplicación Hadamard de dos matrices

from numpy import array
# Definiendo la primera y segunda matriz
A, B = array([
    [1, 2, 3],
    [4, 5, 6]
]),  array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)
print(B)
# Multiplicando las matrices
C = A * B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


### EJEMPLO 5

In [5]:
# División de dos matrices

from numpy import array
# Definiendo la primera y segunda matriz
A, B = array([
    [1, 2, 3],
    [4, 5, 6]
]),  array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)
print(B)
# Dividiendo las matrices
C = A / B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1. 1. 1.]
 [1. 1. 1.]]


### EJEMPLO 6
La función que se utiliza para realizar esta operación es `dot()`, o bien, podemos ocupar el operador `@`.

In [2]:
# Producto punto de matrices

from numpy import array
# Definiendo la primera y segunda matriz
A, B = array([
    [1, 2, 3],
    [4, 5, 6]
]),  array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(A)
print(B)
# Multiplicando las matrices
C = A.dot(B)
print(C)
# Usando el operador @
print(A @ B)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[22 28]
 [49 64]]
[[22 28]
 [49 64]]


### EJEMPLO 7
La función que se utiliza para realizar esta operación es `dot()`.

In [3]:
# Multiplicación de matriz con vector

from numpy import array
# Definiendo la matriz y el vector
A, v = array([
    [1, 2, 3],
    [4, 5, 6]
]),  array([1, 2, 3])
print(A)
print(v)
# Multiplicando la matriz y el vector
C = A.dot(v)
print(C)

[[1 2 3]
 [4 5 6]]
[1 2 3]
[14 32]


### EJEMPLO 8

In [4]:
# Multiplicación de una matriz por un escalar

from numpy import array
# Definiendo la matriz y el escalar
A, b = array([
    [1, 2, 3],
    [4, 5, 6]
]),  2
print(A)
print(b)
# Multiplicando la matriz y el escalar
C = A * b
print(C)

[[1 2 3]
 [4 5 6]]
2
[[ 2  4  6]
 [ 8 10 12]]
