### EJEMPLO 1
Podemos transponer una matriz utilizando el atributo `T.

In [2]:
# Transponer una matriz

from numpy import array
# Definiendo la matriz
A = array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(A)
# Calculando la transpuesta
C = A.T
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


### EJEMPLO 2
Es necesario utilizar la función `inv()` para invertir una matriz.

In [1]:
# Inversa de una matriz

from numpy import array
from numpy.linalg import inv
# Definiendo la matriz
A = array([
    [1, 2],
    [3, 4]
])
print(A)
# Invirtiendo la matriz
B = inv(A)
print(B)
# Multiplicando A y B
I = A.dot(B)
print(I)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


### EJEMPLO 3
Para obtener la traza de la matriz, debemos ocupar la función `trace()`.

In [3]:
# Traza de una matriz

from numpy import array, trace
# Definiendo la matriz
A = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(A)
# Calculando la traza
B = trace(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


### EJEMPLO 4
El determinante de una matriz se calcula usando la función `det()`.

In [5]:
# Determinante de una matriz

from numpy import array
from numpy.linalg import det
# Definiendo la matriz
A = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(A)
# Calculando el determinante de A
B = det(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-9.51619735392994e-16


### EJEMPLO 5
Usando la función `matrix_rank()` podemos obtener el rango de una matriz o vector.

In [6]:
# Rango de una vector

from numpy import array
from numpy.linalg import matrix_rank
# Rango
v1 = array([1, 2, 3])
vr1 = matrix_rank(v1)
# Rango cero
v2 = array([0, 0, 0, 0, 0])
vr2 = matrix_rank(v2)
print(v1)
print(vr1)
print(v2)
print(vr2)

[1 2 3]
1
[0 0 0 0 0]
0


### EJEMPLO 6

In [11]:
# Rango de una matriz

from numpy import array
from numpy.linalg import matrix_rank
# Rango 0
M0 = array([
    [0, 0],
    [0, 0]
])
MR0 = matrix_rank(M0)
# Rango 1
M1 = array([
    [1, 2],
    [1, 2]
])
MR1 = matrix_rank(M1)
# Rango 2
M2 = array([
    [1, 2],
    [3, 4]
])
MR2 = matrix_rank(M2)
print(M0)
print(MR0)
print(M1)
print(MR1)
print(M2)
print(MR2)

[[0 0]
 [0 0]]
0
[[1 2]
 [1 2]]
1
[[1 2]
 [3 4]]
2
