### EJEMPLO 1
La función para poder calcular la norma $L^1$ es `norm()` indicando en el segundo parámetro un $1$.

In [1]:
# Norma L1

from numpy import array
from numpy.linalg import norm
# Definiendo el vector
a = array([1, 2, 3])
print(a)
# Calculando la norma
l1 = norm(a, 1)
print(l1)

[1 2 3]
6.0


### EJEMPLO 2
La función para poder calcular la norma $L^2$ es `norm()`.

In [2]:
# Norma L2

from numpy import array
from numpy.linalg import norm
# Definiendo el vector
a = array([1, 2, 3])
print(a)
# Calculando la norma
l2 = norm(a)
print(l2)

[1 2 3]
3.7416573867739413


### EJEMPLO 3
La función para poder calcular la norma $L^\infty$ es `norm()` indicando en el segundo parámetro un `inf`.

In [4]:
# Norma Linf

from math import inf
from numpy import array
from numpy.linalg import norm
# Definiendo el vector
a = array([1, 2, 3])
print(a)
# Calculando la norma
linf = norm(a, inf)
print(linf)

[1 2 3]
3.0
