# Limitation with Array Arithmetic
Se puede aplicar directamente operaciones aritméticas en los arreglos NumPy, como adición y substracción. 

In [1]:
# Aritmética en arreglos NumPy

from numpy import array
# Definiendo los arreglos
a, b = array([1, 2, 3]), array([1, 2, 3])
# Sumando y restando a y b
print(a + b, a - b)

[2 4 6] [0 0 0]


Estrictamente, esto puede ser usado en arreglos que tienen la misma dimensión y dimensiones con el mismo tamaño, sin embargo, en NumPy existe un método para realizar operaciones aritméticas con arreglos de diferentes tamaños.

# Array Broadcasting
Broadcasting es el nombre que recibe el método usado en NumPy para permitir las operaciones aritméticas entre arreglos de diferentes tamaños. Este método no sólo es utilizado en NumPy, sino que también en Theano, TensorFlow y Octave. 
Para lograr esto, NumPy no duplica el arreglo más pequeño para hacerlo del mismo tamaño que el grande; usa las estructuras existentes en la memoria para obtener este mismo resultado. 

# Broadcasting in NumPy
### Scalar and One-Dimensional Array
Un valor o escalar puede ser usado en una operación aritmética en un arreglo unidimensional sin necesidad de duplicarlo hasta crear un arreglo del mismo tamaño que el primero.


In [2]:
# Broadcast un escalar a un arreglo unidimensional

from numpy import array
# Definiendo el arreglo
a = array([1, 2, 3])
print(a)
# Definiendo el escalar
b = 3
print(b)
# Broadcast
c = a + b
print(c)

[1 2 3]
3
[4 5 6]


### Scalar and Two-Dimensional Array
De igual manera, un esaclar puede ser usado en un arreglo bidimensional. 

In [4]:
# Broadcast un escalar a un arreglo bidimensional

from numpy import array
# Defiendo el arreglo
A = array([
    [1, 2, 3],
    [1, 2, 3]])
print(A)
# Definiendo el escalar
b = 3
print(b)
# Broadcast
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
3
[[4 5 6]
 [4 5 6]]


### One-Dimensional and Two-Dimensional Arrays
Un arreglo unidimensional puede ser usado en una operación aritmética en un arreglo bidimensional. 

In [10]:
# Broadcast un arreglo unidimensional a un arreglo bidimensional

from numpy import array
# Definiendo el arreglo bidimensional
A = array([
    [1, 2, 3],
    [1, 2, 3]])
print(A)
# Definiendo el arreglo unidimensional
b = array([1, 2, 3])
print(b)
# Broadcast
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
[1 2 3]
[[2 4 6]
 [2 4 6]]


# Limitations of Broadcasting
Las opraciones aritméticas, incluyendo el broadcasting, pueden ser realizadas siempre y cuando la escala de cada dimensión en lo arreglos sean iguales, o que uno tenga una dimensión de tamaño 1. Éstas son consideradas al revés, esto es, se consideran primero las columnas antes que las filas y, en dado caso de que las dimensiones no coincidan, el broadcasting no puede ser realizado.

In [8]:
# Error en el broadcasting

from numpy import array
# Definiendo el arreglo bidimensional
A = array([
    [1, 2, 3],
    [1, 2, 3]])
print(A.shape)
# Definiendo el arreglo unidimensional
b = array([1, 2])
print(b.shape)
# Intentando aplicar el broadcast
C = A + b
print(C)

(2, 3)
(2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 