# NumPy N-dimensional Array

En NumPy se ocupan los ndarray, que son arreglos que contienen data del mismo tipo. El tipo de dato puede ser visto a través de dtype, la dimensión con shpae.
Una forma sencilla de crear un arreglo es ocupando `array()`.

In [3]:
# Importando la librería
from numpy import array
# Creando arreglo
l = [1.0, 2.0, 3.0]
a = array(l)
# Imprimiendo el arreglo
print(a)
# Imprimiendo la dimensión
print(a.shape)
# Imprimiendo el tipo de dato
print(a.dtype)

[1. 2. 3.]
(3,)
float64


# Functions to Create Arrays

### Empty

La función `empty()` creará un arreglo con dimensión específica. Su argumento es un arreglo o tuple que especifica la dimensión. Los valores o contenido que tenga este arreglo será totalmente aleatorio. 

In [5]:
# Creando un arreglo vacío
from numpy import empty
a = empty([3,3]) # Crea un arreglo de 3x3
print(a)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.34380289e-321]
 [1.78019354e-306 2.56761491e-312 0.00000000e+000]]


### Zeros

La función `zeros()` crea un nuevo arreglo con tamaño especificado, el cual contendrá puros valores 0.

In [6]:
# Creando un arreglo de ceros
from numpy import zeros
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Ones

La función `ones()` crea un nuevo arreglo con tamaño específico, el cual contendrá puros valores 1.

In [8]:
# Creando un arreglo de unos
from numpy import ones
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


# Combining Arrays

### Vertical Stack

Dados dos o más arreglos, se pueden juntar verticalmente usando `vstack()`. Por ejemplo, dados dos arreglos unidimensionales, se puede crear un nuevo arreglo bidimensional al juntarlos.

In [11]:
# Creando un arreglo con vstack
from numpy import array, vstack
a1 = array([1, 2, 3])
print(a1)
a2 = array([4, 5, 6])
print(a2)
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


### Horizontal Stack

Dados dos o más arreglos, se pueden juntar horizontalmente usando `hstack()`. Por ejemplo, dados dos arreglos unidimensionales, se puede crear un nuevo arreglo unidimensional con las columnas de ambos arreglos concatenados.

In [13]:
# Creando un arreglo con hstack
from numpy import array, hstack
a1 = array([1, 2, 3])
print(a1)
a2 = array([4, 5, 6])
print(a2)
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)
